from turtle import Turtle, Screen
Cur = Turtle()
Cur.color("white")
Cur.forward(50)
Cur.right(90)
Cur.color("red")
Cur.forward(50)
Cur.right(90)
Cur.forward(100)
Cur.right(90)
Cur.forward(100)
Cur.right(90)
Cur.forward(100)
Cur.right(90)
Cur.forward(50)
screen = Screen()
screen.exitonclick()